# python interpreter
# by default ubuntu 18.04 using python3
ansible_python_interpreter: /usr/bin/python3

# kubernetes config
kubeadmin_config: /etc/kubernetes/admin.conf
kubernetes_token: b0f7b8.8d1767876297d85c

# Kubernetes Cluster
kubernetes:
  cluster:
  - name: k8s
    install_worker: true
    install_network: true
    network:
      type: flannel
      pod_network_cidr: "10.244.0.0/16"
    master:
      - name: master
        ip: 10.200.200.150
    worker: 
      - name: worker0
        ip: 10.200.200.151
      - name: worker1
        ip: 10.200.200.152
  - name: hk8s
    install_worker: true
    install_network: true
    network:
      type: calico
      pod_network_cidr: "192.168.0.0/16"
    master: 
      - name: master
        ip: 10.200.200.153
    worker: 
      - name: worker0
        ip: 10.200.200.154
      - name: worker1
        ip: 10.200.200.155
  - name: bk8s
    install_worker: true
    install_network: true
    network:
      type: flannel
      pod_network_cidr: "10.244.0.0/16"
    master: 
      - name: master
        ip: 10.200.200.156
    worker: 
      - name: worker0
        ip: 10.200.200.157
  - name: wk8s
    install_worker: true
    install_network: true
    network:
      type: flannel
      pod_network_cidr: "10.244.0.0/16"
    master: 
      - name: master
        ip: 10.200.200.158
    worker: 
      - name: worker0
        ip: 10.200.200.159
      - name: worker1
        ip: 10.200.200.160
  - name: ek8s
    install_worker: true
    install_network: true
    network:
      type: flannel
      pod_network_cidr: "10.244.0.0/16"
    master: 
      - name: master
        ip: 10.200.200.161
    worker: 
      - name: worker0
        ip: 10.200.200.162
      - name: worker1
        ip: 10.200.200.163
  - name: ik8s
    install_worker: false
    install_network: false
    master: 
      - name: master
        ip: 10.200.200.164
    worker: 
      - name: worker0
        ip: 10.200.200.165

  # management node
  # this nodes used to access all kubernetes cluster
  management:
    name: management
    ip: 10.200.200.166

  # deployer node
  deployer:
    ip: 10.200.200.1
