- name: create script directory
  file:
    path: ~/script/{{ pod_name }}
    state: directory

- name: copy all template
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    mode: a+x
  with_items:
    - { src: 'cluster1.sh.j2', dest: '~/script/{{ pod_name }}/cluster1.sh' }
    - { src: 'cluster2.sh.j2', dest: '~/script/{{ pod_name }}/cluster2.sh' }
    - { src: 'cluster3.sh.j2', dest: '~/script/{{ pod_name }}/cluster3.sh' }
    - { src: 'management.sh.j2', dest: '~/script/{{ pod_name }}/management.sh' }

- name: Create VM
  shell: "bash {{item}}"
  with_items:
  - '~/script/{{ pod_name }}/cluster1.sh'
  - '~/script/{{ pod_name }}/cluster2.sh'
  - '~/script/{{ pod_name }}/cluster3.sh'
  - '~/script/{{ pod_name }}/management.sh'


