- name: create script directory
  file:
    path: ~/script/{{ vm_name }}
    state: directory

- name: copy all template
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    mode: a+x
  with_items:
    - { src: 'cluster.sh.j2', dest: '~/script/{{ vm_name }}/cluster.sh' }
    - { src: 'management.sh.j2', dest: '~/script/{{ vm_name }}/management.sh' }

- name: Create VM
  shell: "bash ~/script/{{ vm_name }}/cluster.sh"


- name: Create Management
  shell: "bash ~/script/{{ vm_name }}/management.sh"

  



