- name: Create VM & Configuring IP
  hosts: deployer
  roles:
    - node-provisioning

- name: Node Setup
  hosts: cluster1, cluster2, cluster3
  roles:
    - node-setup

- name: Master Setup
  hosts: master1, master2, master3
  roles:
    - master-setup

- name: Worker Setup
  hosts: worker1, worker2, worker3
  roles:
    - worker-setup

- name: Flannel
  hosts: master1, master2, master3
  roles:
    - flannel

- name: kubeconfig-deployer
  hosts: deployer
  roles:
    - deployer-kubeconfig

- name: kubeconfig-management
  hosts: management
  roles:
    - management-kubeconfig