apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example-for-unavailable
  name: example-for-unavailable
spec:
  replicas: 5
  selector:
    matchLabels:
      app: example-for-unavailable
  template:
    metadata:
      labels:
        app: example-for-unavailable
    spec:
      containers:
      - image: alpine
        name: alpine
        command:
        - /bin/sh
        - "-c"
        - "sleep 60m"
