- name: create script directory
  file:
    path: ~/.kube/
    state: directory

- name: change configuration
  shell: |
    sed -i "s/name: kubernetes/name: kubernetes1/g" ~/cluster1
    sed -i "s/cluster: kubernetes/cluster: kubernetes1/g" ~/cluster1
    sed -i "s/user: kubernetes-admin/user: kubernetes-admin1/g" ~/cluster1
    sed -i "s/name: kubernetes1-admin@kubernetes/name: cluster1/g" ~/cluster1
    sed -i "s/name: kubernetes1-admin/name: kubernetes-admin1/g" ~/cluster1
    sed -i '/current-context: kubernetes-admin@kubernetes/d' ~/cluster1

    sed -i "s/name: kubernetes/name: kubernetes2/g" ~/cluster2
    sed -i "s/cluster: kubernetes/cluster: kubernetes2/g" ~/cluster2
    sed -i "s/user: kubernetes-admin/user: kubernetes-admin2/g" ~/cluster2
    sed -i "s/name: kubernetes2-admin@kubernetes/name: cluster2/g" ~/cluster2
    sed -i "s/name: kubernetes2-admin/name: kubernetes-admin2/g" ~/cluster2
    sed -i '/current-context: kubernetes-admin@kubernetes/d' ~/cluster2

    sed -i "s/name: kubernetes/name: kubernetes3/g" ~/cluster3
    sed -i "s/cluster: kubernetes/cluster: kubernetes3/g" ~/cluster3
    sed -i "s/user: kubernetes-admin/user: kubernetes-admin3/g" ~/cluster3
    sed -i "s/name: kubernetes3-admin@kubernetes/name: cluster3/g" ~/cluster3
    sed -i "s/name: kubernetes3-admin/name: kubernetes-admin3/g" ~/cluster3
    sed -i '/current-context: kubernetes-admin@kubernetes/d' ~/cluster3

- name: change configuration
  shell: KUBECONFIG=~/cluster1:~/cluster2:~/cluster3 kubectl config view --flatten >> ~/.kube/config